### ISSUE TITLE
Multiple Issues...

### ISSUE THREAD

**Issue by jonesnotathome** [failociraptor/tadpoles-scraper#2]
I've made significant edits to your code and would like to provide it to you for merging into your project.
Issues Addressed:
-Multiple files with same creation date/time
-PDF files
-jpg files with transparency
-Logging
-Single executable file

**Comment by JonathanKringen** [comment]
> I keep getting

Starting up, grabbing initial parameters.
Job "GatedScraper.fire_job (trigger: interval[0:00:15], next run at: 2020-07-29 19:00:22 CDT)" raised an exception
Traceback (most recent call last):
  File "site-packages\apscheduler\executors\base.py", line 125, in run_job
  File "gatedScraper.py", line 59, in fire_job
    currentItem['callback'](resp, currentItem['params'])
  File "tadpoles.py", line 77, in parentScrape
  File "json\__init__.py", line 341, in loads
TypeError: the JSON object must be str, bytes or bytearray, not NoneType

when I try to run the executable.
> 
> I've made significant edits to your code and would like to provide it to you for merging into your project.
> Issues Addressed:
> -Multiple files with same creation date/time
> -PDF files
> -jpg files with transparency
> -Logging
> -Single executable file
> 
> [tadpoles.zip](https://github.com/failociraptor/tadpoles-scraper/files/4875397/tadpoles.zip)

**Comment by jonesnotathome** [comment]
What parameters are you running the executable with (bat file)? Make sure you put the cookie information in quotes when you pass as parameter.

**Comment by failociraptor** [comment]
Ha, sorry I didn't realize people were actually using this.  I'm happy to look at a PR, but I'm not going to download and run a random ZIP, sorry.
